### ISSUE TITLE
PCIe x1 compatibility

### ISSUE THREAD

**Issue by CedricDly** [TI-Bonn/vercolib_pcie#1]
Hi,
Can Vercolib be used with a PCIe 1x Gen2 FPGA ?
Regards!

**Comment by SchuellerSe** [comment]
Hi,

currenly we only have a ready-to-use endpoint configuration for 7 Series FPGAs with 8 lanes.
However, as long as you're using an FPGA that is compatible with Xilinx' Gen2 IP-Core, it's probably fairly straightforward to adapt the endpoint module for single lane setups.

**Comment by CedricDly** [comment]
Thank you for the answer !
